// Font Awesome setup file (update to include new icon for card view)
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faChevronRight,
  faEarthAsia,
  faMapLocationDot,
  faFileInvoice,
  faDatabase,
  faClipboardList,
  faStreetView,
  faCircleCheck,
  faArrowRight,
  faArrowLeft,
  faInfo,
  faAngleRight,
  faAngleDown,
  faChalkboardUser,
  faChartLine,
  faGlobe,
  faUser,
  faLock,
  faCalculator,
  faSearch,
  faRotateLeft,
  faHeart,
  faPlus,
  faRepeat,
  faPhone,
  faEnvelope,
  faPlay,
  faStop,
  faCheck,
  faReply,
  faClock,
  faCheckCircle,
  faCancel,
  faVoteYea,
  faGavel,
  faHandHolding,
  faInbox,
  faPause,
  faRobot,
  faAddressCard,
  faTable,
  faTasks,
  faWrench,
  faTruck,
} from '@fortawesome/free-solid-svg-icons';
import { faCircleCheck as faCircleCheckRegular } from '@fortawesome/free-regular-svg-icons';


// Add icons to the Font Awesome library
library.add(
  faChevronRight,
  faEarthAsia,
  faMapLocationDot,
  faFileInvoice,
  faDatabase,
  faClipboardList,
  faStreetView,
  faCircleCheck,
  faCircleCheckRegular,
  faArrowRight,
  faArrowLeft,
  faInfo,
  faAngleRight,
  faAngleDown,
  faChalkboardUser,
  faChartLine,
  faGlobe,
  faUser,
  faLock,
  faCalculator,
  faSearch,
  faRotateLeft,
  faHeart,
  faPlus,
  faRepeat,
  faPhone,
  faEnvelope,
  faPlay,
  faStop,
  faCheck,
  faReply,
  faCancel,
  faVoteYea,
  faGavel,
  faHandHolding,
  faInbox,
  faPause,
  faClock,
  faCheckCircle,
  faRobot,
  faAddressCard,
  faTable,
  faTasks,
  faWrench,
  faTruck,
);

// Function to initialize Font Awesome in a Vue app
export function initFontawesome(app) {
  app.component('font-awesome-icon', FontAwesomeIcon);
}
