export const ORGANIZATIONS = 'ORGANIZATIONS'
export const ORG_TYPES = 'ORG_TYPES'

export const ORGANIZATION = 'ORGANIZATION'

export const USER_EXTRA_ROLES = "USER_EXTRA_ROLES"
export const USER_EXTRA_ROLE = "USER_EXTRA_ROLE"

export const ORGANIZATION_MAX_PERMISSIONS = 'ORGANIZATION_MAX_PERMISSIONS'
export const EMPLOYEE_STANDARD_PERMISSIONS = 'EMPLOYEE_STANDARD_PERMISSIONS'
